using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CloudLib;
using CloudLib.Models;
using ConsoleTester.Options;
using CsvHelper;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using SlackLib;
using SlackLib.Messages;

namespace ConsoleTester
{
    /// <summary>
    /// This class knows what to do with parsed commands
    /// </summary>
    public class CommandHandler 
    {
        private readonly ILogger<CommandHandler> _logger;
        private readonly IStorage _storage;
        private readonly SlackWrapper _slackWrapper;
        public CommandHandler(ILogger<CommandHandler> logger, IStorage storage, SlackWrapper slackWrapper)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _storage = storage ?? throw new ArgumentNullException(nameof(storage));
            _slackWrapper = slackWrapper ?? throw new ArgumentNullException(nameof(slackWrapper));
        }

        public async Task HandleGetQuestionnaires(QuestionnairesOption option)
        {
            _logger.LogTrace("Getting all questionaires");
            var result = await _storage.GetQuestionnaires();
            foreach (var questionaire in result)
            {
                _logger.LogInformation("- {created} {channel} {questionnaireId} {question} {answers}", questionaire.Created, questionaire.Channel, questionaire.QuestionaireId, questionaire.Question, questionaire.AnswerOptions);
            }
        }

        public async Task HandleCreateQuestionnaires(CreateQuestionnaireOption option)
        {
            try 
            {
                _logger.LogTrace("Creating questionnaire from file {file}", option.QuestionnaireFile);

                var json = await File.ReadAllTextAsync(option.QuestionnaireFile);
                var questionnaire = JsonConvert.DeserializeObject<Questionnaire>(json);
                _logger.LogDebug("Questionnaire deserialized, question {0}", questionnaire.Question);

                var questionnaireDto = new QuestionnaireEntity(questionnaire.QuestionId, option.Channel)
                {
                    QuestionaireId = questionnaire.QuestionId,
                    Channel = option.Channel,
                    Created = DateTime.UtcNow,
                    Question = questionnaire.Question,
                    AnswerOptions = string.Join(';', questionnaire.AnswerOptions)
                };
                await _storage.InsertOrMerge(questionnaireDto);
                
                await _slackWrapper.SendQuestionaire(option.Channel, questionnaire);
                _logger.LogInformation("Questionnaire created from file {0}.", option.QuestionnaireFile);
            }
            catch (ChannelWebHookMissingException)
            {
                _logger.LogError("No webhook configured for {channel}. Please add channel webhook before posting to channel", option.Channel);
            }
            catch (SlackLibException exception)
            {
                _logger.LogDebug(exception, "SlackLibException encountered while trying to create questionnaire from file {file}", option.QuestionnaireFile);
                _logger.LogCritical("Unable to send message to Slack. Make sure that Slack WebHook configuration is correct.");
            }
            catch (IOException exception)
            {
                _logger.LogDebug(exception, "IOException encountered while trying to create questionnaire from file {file}", option.QuestionnaireFile);
                _logger.LogCritical("Unable to read file {0}. Possible reasons: File doesn't exists, file name is in invalid format, required permissions ar missing.  Unable to create questionnaire. Aborting...", option.QuestionnaireFile);
            }
            catch (JsonReaderException exception)
            {
                _logger.LogDebug(exception, "JsonReaderException encountered while trying to create questionnaire from file {file}", option.QuestionnaireFile);
                _logger.LogCritical("Unable to parse questionnaire from file {file}. Please make sure that file contains correct JSON. To be sure that file can be parsed, use the template generated by this program. Unable to create questionnaire. Abortting...", option.QuestionnaireFile);
            }
        }

        public async Task HandleGetAnswers(AnswersOption option)
        {
            _logger.LogTrace("Getting {questionnaireId} answers", string.IsNullOrWhiteSpace(option.QuestionnaireId) ? "all" : option.QuestionnaireId);
            var result = await _storage.GetAnswers(option.QuestionnaireId);
            _logger.LogDebug("Found {count} answers", result.Count());
            foreach (var answer in result)
            {
                _logger.LogInformation("- {questionnaireId} {answer} {time} {answerer}", answer.QuestionnaireId, answer.Answer, answer.Timestamp, answer.Answerer);
            }

            if (!string.IsNullOrWhiteSpace(option.OutputCsvFile))
            {
                using (var writer = new StreamWriter(option.OutputCsvFile))
                using (var csv = new CsvWriter(writer))
                {    
                    csv.WriteRecords(result);
                }
            }

            _logger.LogInformation("Answers retrieved.");
        }

        public async Task HandleDelete(DeleteOption option)
        {
            _logger.LogTrace("Deleting all questionnaires and answers");
            await _storage.DeleteAll();
            _logger.LogInformation("All items deleted.");
        }

        public async Task HandleGenerateTemplate(GenerateQuestionnaireTemplateOption option)
        {
            _logger.LogTrace("Generating a questionnaire template");

            var example = new Questionnaire
            {
                Question = "I said hey, what's going on?",
                AnswerOptions = new string []
                {
                    "I try all the time",
                    "in this institution",
                    "hey yeah yeah",
                    ":partyparrot:"
                }
            };
            string json = JsonConvert.SerializeObject(example, Formatting.Indented);
            await File.WriteAllTextAsync(option.FileName, json);
            _logger.LogInformation("Questionnaire template file '{file}' created.", option.FileName);
        }

        public async Task HandleWebhookAdd(AddWebhookOption option)
        {
            _logger.LogTrace("Adding or updating webhook for channel {channel}", option.Channel);

            await _storage.InsertOrMerge(option.Channel, option.WebHookUrl);
        }
    }
}