using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CloudLib;
using CloudLib.Models;
using ConsoleTester.Options;
using CsvHelper;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using SlackLib;
using SlackLib.Messages;

namespace ConsoleTester
{
    /// <summary>
    /// This class knows what to do with parsed commands
    /// </summary>
    public class CommandHandler 
    {
        private readonly ILogger<CommandHandler> _logger;
        private readonly IServiceProvider _serviceProvider;
        public CommandHandler(IServiceProvider serviceProvider)
        {
            _logger = serviceProvider.GetService<ILogger<CommandHandler>>();
            _serviceProvider = serviceProvider;
        }

        public async Task HandleGetQuestionnaires(QuestionnairesOption option)
        {
            _logger.LogTrace("Getting all questionaires");
            var storage = _serviceProvider.GetService<IStorage>();
            var result = await storage.GetQuestionnaires();
            foreach (var questionaire in result)
            {
                _logger.LogInformation("- {0} {1} {2} {3}", questionaire.Channel,  questionaire.QuestionaireId, questionaire.Question, questionaire.Created);
            }
        }

        public async Task HandleCreateQuestionnaires(CreateQuestionnaireOption option)
        {
            try 
            {
                _logger.LogTrace("Creating questionnaire from file {0}", option.QuestionnaireFile);
                var storage = _serviceProvider.GetService<IStorage>();
                var slackWrapper = _serviceProvider.GetService<SlackWrapper>();

                var json = await File.ReadAllTextAsync(option.QuestionnaireFile);
                var questionnaire = JsonConvert.DeserializeObject<Questionnaire>(json);
                _logger.LogDebug("Questionnaire deserialized, question {0}", questionnaire.Question);

                var questionnaireDto = new QuestionnaireEntity(questionnaire.QuestionId, option.Channel)
                {
                    QuestionaireId = questionnaire.QuestionId,
                    Channel = option.Channel,
                    Created = DateTime.UtcNow,
                    Question = questionnaire.Question
                };
                await storage.InsertOrMerge(questionnaireDto);
                
                await slackWrapper.SendQuestionaire(option.Channel, questionnaire);
                _logger.LogInformation("Questionnaire created from file {0}.", option.QuestionnaireFile);
            }
            catch (ChannelWebHookMissingException)
            {
                _logger.LogError("No webhook configured for {0}. Please add channel webhook before posting to channel", option.Channel);
            }
            catch (SlackLibException exception)
            {
                _logger.LogDebug(exception, "SlackLibException encountered while trying to create questionnaire from file {0}", option.QuestionnaireFile);
                _logger.LogCritical("Unable to send message to Slack. Make sure that Slack WebHook configuration is correct.");
            }
            catch (IOException exception)
            {
                _logger.LogDebug(exception, "IOException encountered while trying to create questionnaire from file {0}", option.QuestionnaireFile);
                _logger.LogCritical("Unable to read file {0}. Possible reasons: File doesn't exists, file name is in invalid format, required permissions ar missing.  Unable to create questionnaire. Abortting...", option.QuestionnaireFile);
            }
            catch (JsonReaderException exception)
            {
                _logger.LogDebug(exception, "JsonReaderException encountered while trying to create questionnaire from file {0}", option.QuestionnaireFile);
                _logger.LogCritical("Unable to parse questionnaire from file {0}. Please make sure that file contains correct JSON. To be sure that file can be parsed, use the template generated by this program. Unable to create questionnaire. Abortting...", option.QuestionnaireFile);
            }
        }

        public async Task HandleGetAnswers(AnswersOption option)
        {
            _logger.LogTrace("Getting {0} answers", string.IsNullOrWhiteSpace(option.QuestionnaireId) ? "all" : option.QuestionnaireId);
            var storage = _serviceProvider.GetService<IStorage>();
            var result = await storage.GetAnswers(option.QuestionnaireId);
            _logger.LogDebug("Found {0} answers", result.Count());
            foreach (var answer in result)
            {
                _logger.LogInformation("- {0} {1} {2} {3}", answer.QuestionnaireId, answer.Answer, answer.Timestamp, answer.Answerer);
            }

            if (!string.IsNullOrWhiteSpace(option.OutputCsvFile))
            {
                using (var writer = new StreamWriter(option.OutputCsvFile))
                using (var csv = new CsvWriter(writer))
                {    
                    csv.WriteRecords(result);
                }
            }

            _logger.LogInformation("Answers retrieved.");
        }

        public async Task HandleDelete(DeleteOption option)
        {
            _logger.LogTrace("Deleting all questionnaires and answers");
            var storage = _serviceProvider.GetService<Storage>();
            await storage.DeleteAll();
            _logger.LogInformation("All items deleted.");
        }

        public async Task HandleGenerateTemplate(GenerateQuestionnaireTemplateOption option)
        {
            _logger.LogTrace("Generating a questionnaire template");

            var example = new Questionnaire
            {
                Question = "Mitenkäs hurisee?",
                AnswerOptions = new string []
                {
                    "Hyvin menee",
                    "Ei se mene",
                    ":feelsbadman:"
                }
            };
            string json = JsonConvert.SerializeObject(example, Formatting.Indented);
            await File.WriteAllTextAsync(option.FileName, json);
            _logger.LogInformation("Questionnaire template file '{0}' created.", option.FileName);
        }

        public async Task HandleWebhookAdd(AddWebhookOption option)
        {
            _logger.LogTrace("Adding or updating webhook for channel {0}", option.Channel);

            var storage = _serviceProvider.GetService<IStorage>();
            await storage.InsertOrMerge(option.Channel, option.WebHookUrl);
        }
    }
}