using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AskBotCore;
using CloudLib;
using CloudLib.Models;
using ConsoleInterface.Options;
using CsvHelper;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using SlackLib;
using SlackLib.Messages;

namespace ConsoleInterface
{
    /// <summary>
    /// This class knows what to do with parsed commands
    /// </summary>
    public class CommandHandler
    {
        private readonly ILogger<CommandHandler> _logger;
        private readonly AskBotControl _control;

        public CommandHandler(ILogger<CommandHandler> logger, AskBotControl control)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _control = control ?? throw new ArgumentNullException(nameof(control));
        }

        public async Task HandleGetQuestionnaires(QuestionnairesOption option)
        {
            _logger.LogTrace("Get all questionnaires activated from console interface.");

            await _control.GetQuestionnaires().ConfigureAwait(false);
        }

        public async Task HandleCreateQuestionnaire(CreateQuestionnaireOption option)
        {
            try
            {
                _logger.LogTrace("Creating questionnaire from file {file}", option.QuestionnaireFile);

                var json = await File.ReadAllTextAsync(option.QuestionnaireFile);
                var questionnaire = JsonConvert.DeserializeObject<Questionnaire>(json);
                _logger.LogDebug("Questionnaire deserialized, question {0}", questionnaire.Question);

                await _control.CreateQuestionnaire(questionnaire, option.Channel, DateTime.UtcNow).ConfigureAwait(false);
                _logger.LogInformation("Questionnaire created from file {0}.", option.QuestionnaireFile);
            }
            catch (IOException exception)
            {
                _logger.LogDebug(exception, "IOException encountered while trying to create questionnaire from file {file}", option.QuestionnaireFile);
                _logger.LogCritical("Unable to read file {0}. Possible reasons: File doesn't exists, file name is in invalid format, required permissions ar missing.  Unable to create questionnaire. Aborting...", option.QuestionnaireFile);
            }
            catch (JsonSerializationException exception)
            {
                _logger.LogDebug(exception, "JsonSerializationException encountered while trying to create questionnaire from file {file}", option.QuestionnaireFile);
                _logger.LogCritical("Unable to parse questionnaire from file {file}. Please make sure that file contains correct JSON. To be sure that file can be parsed, use the template generated by this program. Unable to create questionnaire. Abortting...", option.QuestionnaireFile);
            }
        }

        public async Task HandleGetAnswers(AnswersOption option)
        {
            _logger.LogTrace("Get questionnaire answers activated from console interface.");

            var result = await _control.GetAnswers(option.QuestionnaireId).ConfigureAwait(false);

            if (!string.IsNullOrWhiteSpace(option.OutputCsvFile))
            {
                using (var writer = new StreamWriter(option.OutputCsvFile))
                using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
                {
                    csv.WriteRecords(result);
                }
                _logger.LogInformation("Answers written to file: {file}.", option.OutputCsvFile);
            }
        }

        public async Task HandleDelete(DeleteOption option)
        {
            _logger.LogTrace("Delete all questionnaires and answers activated from console interface.");

            await _control.DeleteAll().ConfigureAwait(false);
        }

        public async Task HandleGenerateTemplate(GenerateQuestionnaireTemplateOption option)
        {
            _logger.LogTrace("Generating a questionnaire template.");

            var example = new Questionnaire
            {
                Question = "I said hey, what's going on?",
                AnswerOptions = new string[]
                {
                    "I try all the time",
                    "in this institution",
                    "hey yeah yeah",
                    ":partyparrot:"
                }
            };
            string json = JsonConvert.SerializeObject(example, Formatting.Indented);
            await File.WriteAllTextAsync(option.FileName, json);
            _logger.LogInformation("Questionnaire template file '{file}' created.", option.FileName);
        }
    }
}